name: Build

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check cache
        id: verify-cache
        run: |
          echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1`"

      - name: Use cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1.1

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: 'Package'
          path: ${{ github.workspace }}/packages/*.deb
